<?php

/**
 * Implements hook_schema().
 */
function misk_contact_us_schema() {
  $schema['misk_contact_us_submissions'] = [
    'description' => 'Stores Contact Us form submissions.',
    'fields' => [
      'id' => [
        'type' => 'serial',
        'not null' => TRUE,
      ],
      'name' => [
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
      ],
      'email' => [
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
      ],
      'age' => [
        'type' => 'int',
        'not null' => TRUE,
      ],
      'message' => [
        'type' => 'text',
        'not null' => TRUE,
      ],
      'created' => [
        'type' => 'int',
        'not null' => TRUE,
      ],
    ],
    'primary key' => ['id'],
  ];

  return $schema;
}
