<?php

/**
 * Implements hook_theme().
 */
function misk_contact_us_theme($existing, $type, $theme, $path) {
  return [
    'contact_form_block' => [
      'variables' => [
        'form' => NULL,
      ],
      'template' => 'contact-form-block',
    ],

    'contact_results' => [
      'template' => 'contact-results',
      'variables' => [
        'title' => NULL,
        'submissions' => [],
      ],
    ],
  ];
}
